### ISSUE TITLE
An error in io.kestra.plugin.singer.taps.Salesforce.  Invalid version: ‘meltano.1.5.0’

### ISSUE THREAD

**Issue by apavel07** [kestra-io/plugin-singer#81]
Hi Team, can you please help with an error in io.kestra.plugin.singer.taps.Salesforce task?

```
id: myflow
namespace: company.team
tasks:
  - id: sf
    type: "io.kestra.plugin.singer.taps.Salesforce"
    # apiType: REST
    apiType: BULK
    startDate: "2024-01-01"
    clientId : some_client_id...
    clientSecret : some_client_secret...
    streamsConfigurations:
    - stream: Lead
      replicationMethod: FULL_TABLE
      # replicationKeys: categoryId
      selected: true
      propertiesPattern:
        - Title
```

--------------------------------
LOG 
--------------------------------
2024-11-25 11:47:41.834Image pulled [python:3.10.12]
2024-11-25 11:47:41.886Container created: fa2e8872c9721c7bb4381dd85575d5c8545b824e6cb1aeccbc8c86af19be647c
2024-11-25 11:47:41.896Volume created: 927fc278a90bd62241bff18de237b3f6034ce2b49c45ad99e32ed51886b280cf
2024-11-25 11:47:42.357Starting command with container id fa2e8872c9721c7bb4381dd85575d5c8545b824e6cb1aeccbc8c86af19be647c [/bin/sh -c set -o errexit
 pip install pip --upgrade > /dev/null
 pip install --target . git+https://gitlab.com/meltano/tap-salesforce.git > /dev/null
 pip install --target . python-json-logger > /dev/null
 chmod -R 755 bin
 find . -type f -name logging.conf | grep “/singer/” | xargs -r cp logging.conf
 ./bin/tap-salesforce --config config.json --discover > discover.json]
 ....
2024-11-25 11:47:54.081pip._vendor.packaging.version.InvalidVersion: Invalid version: ‘meltano.1.5.0’
2024-11-25 11:47:54.167Container deleted: fa2e8872c9721c7bb4381dd85575d5c8545b824e6cb1aeccbc8c86af19be647c
2024-11-25 11:47:54.175Volume deleted: 927fc278a90bd62241bff18de237b3f6034ce2b49c45ad99e32ed51886b280cf
2024-11-25 11:47:54.180io.kestra.core.models.tasks.runners.TaskException: Command failed with code 2
 at io.kestra.plugin.scripts.runner.docker.Docker.run(Docker.java:475)
 at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:157)
 at io.kestra.plugin.singer.AbstractPythonSinger.run(AbstractPythonSinger.java:157)
 at io.kestra.plugin.singer.taps.AbstractPythonTap.discover(AbstractPythonTap.java:146)
 at io.kestra.plugin.singer.taps.AbstractPythonTap.initEnvDiscoveryAndState(AbstractPythonTap.java:63)
 at io.kestra.plugin.singer.taps.AbstractPythonTap.run(AbstractPythonTap.java:80)
 at io.kestra.plugin.singer.taps.AbstractPythonTap.run(AbstractPythonTap.java:36)
 at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:76)
 at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:57)
2024-11-25 11:47:54.180Command failed with code 2 (edited) 

---------------------------------------------------
I've made a bit of experiments.
---------------------------------------------------
I can see from Kestra logs, that it creates docker and runs commands. So I did the same and I got the same error (experiment 1). Then I made the second try and I used coomand from manual on https://gitlab.com/meltano/tap-salesforce. And it was ok.

---- Dockerfile ----
```
FROM python:3.10.12
WORKDIR /app
CMD ["bash"]
```

---- Experiment 1 ----
```
pip install pip --upgrade > /dev/null
pip install --target . git+https://gitlab.com/meltano/tap-salesforce.git > /dev/null
```
----  result -----
`ERROR: pip._vendor.packaging.version.InvalidVersion: Invalid version: ‘meltano.1.5.0’`

---- Experiment 2 ----
```
python3 -m venv venv
source venv/bin/activate
pip install git+https://gitlab.com/meltano/tap-salesforce.git
```
----  result -----
All good, no errors (edited) 

### Environment

Kestra Version: 0.19.11
Operating System (OS/Docker/Kubernetes): Kubernetes

**Comment by Ben8t** [comment]
@mgabelle maybe worth to move this repo https://github.com/singer-io/tap-salesforce -> last change in https://gitlab.com/meltano/tap-salesforce.git are 2 years old while the one from singer team had more recent commits
